apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: devops-git-jenkins-docker-dockerhub-kubernetees
spec:
  selector:
    matchLabels:
      app: devops-git-jenkins-docker-dockerhub-kubernetees
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: devops-git-jenkins-docker-dockerhub-kubernetees
    spec:
      containers:
        - name: devops-git-jenkins-docker-dockerhub-kubernetees
          image: aymen1102/devops-git-jenkins-docker-dockerhub-kubernetees # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: devops-git-jenkins-docker-dockerhub-kubernetees_service
spec:
  selector:
    app: devops-git-jenkins-docker-dockerhub-kubernetees
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
